// entrypoints/twitch.content/hitsquad/views/miniGames/MiniGamesControlsChest.vue
<template>
    <MiniGamesControlsItem
        name="Chest"
        :isGameActive="gameService.isGameEnabled"
        :isSendEnabled
        :sendButtonTooltip
        @send="gameService.sendCommand()"
        @toggle="gameService.toggle()"
    >
        <template #icon="{ classes }">
            <Boxes :size="16" :class="classes" />
        </template>

        <template #indicators v-if="gameService.isRoundRunning">
            <MiniGamesControlsIndicators>
                <MiniGamesControlsTimer :timeout="gameService.timeUntilMessage" />
            </MiniGamesControlsIndicators>
        </template>
    </MiniGamesControlsItem>
</template>

<script setup lang="ts">
import { Boxes } from 'lucide-vue-next';
import { MiniGamesControlsItem, MiniGamesControlsIndicators, MiniGamesControlsTimer } from '@twitch/core';
import { InjectionTokens } from '@twitch/core/injectionTokens';
import { HitsquadStreamStatusService } from '@twitch/hitsquad/modules';
import { HitsquadInjectionTokens } from '@twitch/hitsquad/hitsquadInjectionTokens';

const streamStatusService = inject<HitsquadStreamStatusService>(InjectionTokens.STREAM_STATUS_SERVICE)!;
const gameService = inject(HitsquadInjectionTokens.CHEST_GAME_SERVICE)!;

const isSendEnabled = computed(() => streamStatusService.isMiniGamesAllowed && gameService.isGamePhase || true);

const sendButtonTooltip = computed(() => {
    const disabledMiniGamesNote = 'Mini-game commands are disabled';

    if (streamStatusService.isAntiCheat) {
        return `Anti-cheat is active. ${disabledMiniGamesNote}`;
    }

    if (!streamStatusService.isStreamOk) {
        return `Stream is broken. ${disabledMiniGamesNote}`;
    }

    if (!streamStatusService.isBotWorking) {
        return `Mini-games bot is not working. ${disabledMiniGamesNote}`;
    }

    if (isSendEnabled.value) {
        return `Send ${gameService.command}`;
    }

    return 'Mini-game is not active';
});
</script>

// entrypoints/twitch.content/hitsquad/views/miniGames/MiniGamesControlsChest.svelte
<MiniGamesControlsItem
    isGameActive={gameService.isGameEnabled}
    Icon={Boxes}
    command={gameService.command}
    name="Chest"
    {isSendEnabled}
    {toggle}
    {sendCommand}
>
    {#snippet indicators()}
        {#if gameService.isRoundRunning}
            <MiniGamesControlsIndicators>
                <MiniGamesControlsTimer timeout={gameService.timeUntilMessage} />
            </MiniGamesControlsIndicators>
        {/if}
    {/snippet}
</MiniGamesControlsItem>

<script lang="ts">
import MiniGamesControlsItem from './MiniGamesControlsItem.svelte';
import MiniGamesControlsIndicators from './MiniGamesControlsIndicators.svelte';
import MiniGamesControlsTimer from './MiniGamesControlsTimer.svelte';
import { Container } from 'typedi';
import { StreamStatusService } from '@twitch/modules/stream';
import { getContext } from 'svelte';
import { ChestGameService } from '@twitch/modules/miniGames';
import { Boxes } from '@lucide/svelte';

const streamStatusService = Container.get(StreamStatusService);
const gameService = getContext<ChestGameService>('chest');

const isSendEnabled = $derived(streamStatusService.isMiniGamesAllowed && gameService.isGamePhase);

const sendCommand = () => gameService.sendCommand();
const toggle = (isEnabled: boolean) => isEnabled ? gameService.start() : gameService.stop();
</script>
