// entrypoints/twitch.content/views/AuthView.svelte
<div class="flex flex-row items-center justify-between gap-[16px] w-full rounded-xl p-[12px]">
    <div class="flex-1">
        <h2 class="font-semibold text-gray-800 dark:text-[#efeff1] text-2xl mb-[4px]">HGF-Helper</h2>

        <p class="text-gray-600 dark:text-[#adadb8]">
            Sign in to unlock all the functions
        </p>
    </div>

    <AuthButton classes="px-6 py-4" />
</div>

<script lang="ts">
import { AuthButton } from '@shared/components';
</script>

// entrypoints/twitch.content/core/views/AuthView.vue
<template>
    <div class="flex flex-row items-center justify-between gap-[16px] w-full rounded-xl p-[12px]">
        <div class="flex-1">
            <h2 class="font-semibold text-gray-800 dark:text-[#efeff1] text-2xl mb-[4px]">HGF-Helper</h2>

            <p class="text-gray-600 dark:text-[#adadb8]">
                Sign in to unlock all the functions
            </p>
        </div>

        <AuthButton classes="px-6 py-4" />
    </div>
</template>

<script setup lang="ts">
import { AuthButton } from '@shared/components';
</script>
