// entrypoints/twitch.content/hitsquad/views/streamStatus/StreamStatus.vue
<template>
    <div class="flex items-center gap-[16px]">
        <StreamStatusMiniGames />
        <StreamStatusVideoPlayer />
        <StreamStatusAntiCheat />
    </div>
</template>

<script setup lang="ts">
import StreamStatusMiniGames from './StreamStatusMiniGames.vue';
import StreamStatusAntiCheat from './StreamStatusAntiCheat.vue';
import { StreamStatusVideoPlayer } from '@twitch/core';
</script>

// entrypoints/twitch.content/views/streamStatus/StreamStatus.svelte
<div class="flex items-center gap-[16px]">
    <StreamStatusMiniGames />
    <StreamStatusVideoPlayer />
    <StreamStatusAntiCheat />
</div>

<script lang="ts">
import StreamStatusMiniGames from './StreamStatusMiniGames.svelte';
import StreamStatusVideoPlayer from './StreamStatusVideoPlayer.svelte';
import StreamStatusAntiCheat from './StreamStatusAntiCheat.svelte';
</script>
