// entrypoints/twitch.content/hitsquad/views/streamStatus/StreamStatusMiniGames.vue
<template>
    <StreamStatusItem :ok="streamStatusService.isBotWorking" :tooltip v-slot="{ classes }">
        <Bot :size="18" :class="classes" />
    </StreamStatusItem>
</template>

<script setup lang="ts">
import { Bot } from 'lucide-vue-next';
import { StreamStatusItem } from '@twitch/core';
import { InjectionTokens } from '@twitch/core/injectionTokens';
import { HitsquadStreamStatusService } from '../../modules';

const streamStatusService = inject<HitsquadStreamStatusService>(InjectionTokens.STREAM_STATUS_SERVICE)!;

const tooltip = computed(() => streamStatusService.isBotWorking
    ? 'Mini-games bot is running'
    : 'Mini-games bot is not running. Mini-game commands are on hold'
);
</script>

// entrypoints/twitch.content/views/streamStatus/StreamStatusMiniGames.svelte
<StreamStatusItem Icon={Bot} isOk={streamStatusService.isBotWorking} {tooltip} />

<script lang="ts">
import { Bot } from '@lucide/svelte';
import StreamStatusItem from './StreamStatusItem.svelte';
import { Container } from 'typedi';
import { StreamStatusService } from '@twitch/modules/stream';

const streamStatusService = Container.get(StreamStatusService);

const tooltip = $derived(
    streamStatusService.isBotWorking
        ? 'Mini-games bot is running'
        : 'Mini-games bot is not running. Mini-game commands are on hold'
);
</script>
