// entrypoints/twitch.content/hitsquad/views/miniGames/MiniGamesControls.vue
<template>
    <div class="flex items-center gap-[16px]">
        <MiniGamesControlsHitsquad />
        <MiniGamesControlsChest />
    </div>
</template>

<script setup lang="ts">
import MiniGamesControlsChest from './MiniGamesControlsChest.vue';
import MiniGamesControlsHitsquad from './MiniGamesControlsHitsquad.vue';
</script>

// entrypoints/twitch.content/views/miniGames/MiniGamesControls.svelte
<div class="flex items-center gap-[16px]">
    <MiniGamesControlsHitsquad />
    <MiniGamesControlsLoot />
    <MiniGamesControlsChest />
</div>

<script lang="ts">
import MiniGamesControlsHitsquad from './MiniGamesControlsHitsquad.svelte';
import MiniGamesControlsLoot from './MiniGamesControlsLoot.svelte';
import MiniGamesControlsChest from './MiniGamesControlsChest.svelte';
</script>
